// fe/app/components/Footer.jsx
import React from 'react'

const Footer = async () => {
    const serverDistroResp = await fetch("http://localhost:8000/api/server-distro/", {next: {revalidate: 3600}})
    const serverDistro = (await serverDistroResp.json()).distro
  return (
      <>
      <hr />
      <div>The server is running: {serverDistro}</div>
      </>
  )
}

export default Footer

// fe/src/routes/Footer.svelte
<script>
    let distro = $state("loading...")
    import {onMount} from "svelte"
    onMount(async () => {
        const response = await fetch("http://localhost:8000/api/server-distro/")
        const data = await response.json()
        distro = data.distro
    })
</script>
<p>Server Distro: {distro}</p>
